### ISSUE TITLE
Is SVGKit fit for create SVG using its DOM?

### ISSUE THREAD

**Issue by shuoli84** [SVGKit/SVGKit#102]
I have such needs to create SVG in code, just like a SVG editor. From the API exposed, I can see this library is suit for displaying svg file but may not able to create SVG, am I right?

**Comment by shuoli84** [comment]
It seems all the logic and code are made working one way: xml -> parser -> dom(require setup in parser) -> image. Since the dom require some setup in parser, so manually setup dom won't work.

**Comment by adamgit** [comment]
Yes, but the aim here is to make it "easy" to skip the "xml" and "parser" steps. If you already have an in-memory DOM, pass that direct to SVGKImage.

Equally, make it "easy" to skip the "render" step: instead of rendering, output the SVG back to XML.

...all it needs is for someone to write that code. SVGKit has been _designed_ to do this, but until someone decides to write the code for it, the functionality will be missing, an empty stub.

If you want to try it (should be very easy), I can provide advice/guidance. But I never use DOM in my apps, so I'm not going to write it myself.
