### ISSUE TITLE
Failures using the Analyzer

### ISSUE THREAD

**Issue by jwyld** [SVGKit/SVGKit#156]
Some of the indicated failures are quite serious and should really be fixed.

**Comment by adamgit** [comment]
Some of your comment is unconstructive and should really be re-considered.

**Comment by jwyld** [comment]
I'm serious.  The Analyzer had a number of failures.  I'm certainly not filing an issue for every one of them.  There aren't so many you can't spend a little time to identify which are serious enough to need fixing now.  You, as one of the contributors, or your colleagues would be in the best position to deem the priority and severity of each, possibly with new issues filed when required.

**Comment by adamgit** [comment]
If you won't file an issue for any of them, and you won't make an
assessment of the "priority and severity of each", how are you helping? How
is this Issue helping? What is it you are achieving here?

You claim there are "serious" issues, and you file an Issue - and then
refuse to tell anyone what they are.

The last time I ran the analyser it had NO GENUINE ISSUES - only false
positives, due to the heuristic/guesswork nature of it.

... Maybe something's changed.

... Maybe your Xcode is different from mine.

... Maybe you have a different way of running the analyser.

...but NONE OF THESE can be checked since you have provided literally zero
information.

If you'd read the notes that were presented to you when you created this
Issue, you'd have read the advice that explains "if something is obviously
broken, it is probably only for you - the maintainers would already have
fixed it or hilighted it if it showed up for them".

As it is, you:
- didn't read the notes
- claimed there is some vague "serious" problem, but refused to say what
- gave literally zero info about any actual problem

I suggest you start by reading this, which you skipped:
http://t-machine.org/index.php/2013/12/22/reporting-issues-in-open-source-software/

**Comment by adamgit** [comment]
Closing. If you find any actual issues, please go ahead and create an Issue for them.
