### ISSUE TITLE
Document size

### ISSUE THREAD

**Issue by ghost** [SVGKit/SVGKit#16]
document size differs from the size of the view.. anyone knows why this happens? view size is almost 3.57 times than document size..

**Comment by adamgit** [comment]
Fixed in my transforms branch - https://github.com/adamgit/SVGKit/tree/transforms

The reason: SVG's are required to intelligently auto-resize, and that's quite complex. I've had to change a large amount of code to make this work.

NB: this branch will break your project - some key classes and methods have changed names
