### ISSUE TITLE
SVGKit breaking any project previously using CocoaLumberjack

### ISSUE THREAD

**Issue by michaelfrain** [SVGKit/SVGKit#163]
Creating SVGKit as a static library and adding it to a project previously using CocoaLumberjack breaks the project due to duplicate symbols and header files being added.

**Comment by adamgit** [comment]
As far as I know, there is only one duplicate symbol - the logLevel. Anything else possibly means you've got a mistake with how you're linking your main project. It's easy to get wrong in Xcode, and Apple doesn't document it very well.

For the log-level, it was a problem in Lumberjack that's since been fixed, but someone needs to port the fix over to SVGKit (requires using a different symbol for the library, not ddloglevel!)

c.f. #82 and #154 

The last time I looked, the info on how to do this is on the front page of the Lumberjack project. I thought someone had already done this + merged it, but maybe not?

**Comment by adamgit** [comment]
Now that we've upgraded to Lumberjack 2.x, I believe this problem has gone away - if not, please re-open.

Also potentially c.f. https://github.com/SVGKit/SVGKit/issues/324
