### ISSUE TITLE
parse from a NSString?

### ISSUE THREAD

**Issue by elprl** [SVGKit/SVGKit#18]
Not really an issue, but more of a question, how could one parse an svg file that is stored in memory within an xml string (NSString). At the moment, in order to use SVGKit with svg files downloaded over the internet, I would have to save the xml string to file first, then load from disk? Is that correct? I don't see something like an -initWithString:(NSString *)xmlString in the SVGDocument class.

**Comment by adamgit** [comment]
My experimental branch has a fix for this:

https://github.com/adamgit/SVGKit/tree/transforms

...instead of loading files directly, SVGKit loads an interface. I've already done an implementation that loads "files from the web via HTTP", and of course one that loads "files from the local disk". Adding one that loads "a plain string" would only be about 10 lines of code.

have a look at the SVGKSource class - this is the generic "source of an SVG file" part

**Comment by adamgit** [comment]
Created a wishlist for new features - c.f.:

https://github.com/SVGKit/SVGKit/wiki/Wishlist
