### ISSUE TITLE
Creating SVG image with ImageNamed issue/bug

### ISSUE THREAD

**Issue by aykutersahin** [SVGKit/SVGKit#188]
After changing Dom document attributes of the svg image, creating the same SVGImage  with imageNamed parameter on new variable doesn't shows the original image. It shows the changed image, Also the parameter "ENABLE_GLOBAL_IMAGE_CACHE_FOR_SVGKIMAGE_IMAGE_NAMED"  (0 or 1) doesn't change anything.

My svg image is (green square) : 
?xml version="1.0" standalone="no"?>
!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd
svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100px" height="100px">
  rect id="asd" width="100" height="100" x="0" y="0" fill="rgb(0, 255, 0)"/>
/svg>

First i load and svg file;
SVGKImage _svgImage = [SVGKImage imageNamed:@"svgtest"];
SVGKImageView_ svgImageView = [[SVGKLayeredImageView alloc] initWithSVGKImage:svgImage];
[self.view addSubview:svgImageView];

After that i change the svg images fill attribute and make the square "red" with dom document :
NodeList *list = [obj.element getElementsByTagName:@"rect"];
for (Element *svgElement in list){
    [svgElement  setAttributeNS:@"http://www.w3.org/2000/svg" qualifiedName:@"fill" value:@"rgb(255, 0, 0)"];
}
[obj.image CALayerTree];

And after that i load same image file to different variable:
SVGKImage _svgImage2 = [SVGKImage imageNamed:@"svgtest"];
SVGKImageView_ svgImageView2 = [[SVGKLayeredImageView alloc] initWithSVGKImage:svgImage2];
[self.view addSubview:svgImageView2];

And it pops up red. As you can see i did not change the second variables dom document but it looks like changed. When i use the creation [SVGKImage imageWithContentsOfFile:imagePath]; , it shows the original image without any change.

**Comment by adamgit** [comment]
Yep, it's a bug.

(what's happening: the "cache" here is implemented by keeping a pointer to the in-memory DOM. Originally, we didn't allow live editing of the DOM, so this was OK.

But now we do allow editing. So the implementation is now wrong.)

Ideally, the DOM should be a "copy-on-write" data structure, so that changing it leaves the original cached for new calls to imageNamed:. Ideas on implementing / converting to that are welcome here.

Or, alternatively, a more intelligent / better designed cache.

NB: the cache copies Apple's design for UIImage, we're keeping it :).
NB: the cache makes a HUGE performance difference if you're reparsing a file multiple times in lifetime of an app.

**Comment by Svantulden** [comment]
That makes sense. I ran into the same problem for my use case when re-using an SVG file and coloring it differently. 

Is there a current workaround for this problem? I.e. can I use another method to load the SVG file instead of `imageNamed` without using the image cache?

**Comment by adamgit** [comment]
You can explicitly decache/recache it by requesting a newcalayertree (see 
the method of that name).

**Comment by Svantulden** [comment]
Thanks for your blazing fast response! How would I use this method exactly? 

I am using it like: 

``` Objective-C
SVGKImage* containerSvg = [SVGKImage imageNamed:@"droplet_svg_icon.svg"];
[containerSvg newCALayerTree];
// ... Color the SVG and add it to a subview
```

But this doesn't seem to work, so I think I am calling it wrong.

**Comment by adamgit** [comment]
How can newlayertree use your changes if you call it BEFORE you've made them?

**Comment by Svantulden** [comment]
I think I wasn't clear enough of how I use the `SVGKImage`. 

I have a list of SVG icons I need to show which all have the same source SVG, but get colored differently for each item. So I call this every time I recolor the next icon in the list: 

``` Objective-C
SVGKImage* containerSvg = [SVGKImage imageNamed:@"droplet_svg_icon.svg"];
SVGDocument *domDoc = containerSvg.DOMDocument;

SVGElement *tophalf = (SVGElement*)[domDoc getElementById:@"Tophalf"];
[tophalf setAttributeNS:@"http://www.w3.org/2000/svg" qualifiedName:@"fill" value:custom_value];
SVGElement *bottomhalf = (SVGElement*)[domDoc getElementById:@"Bottomhalf"];
[bottomhalf setAttributeNS:@"http://www.w3.org/2000/svg" qualifiedName:@"fill" value:custom_value];
```

After that I use an `SVGKFastImageView` to display the `SVGKImage` icons, but like @aykutt I am getting one color for all the icons (the last color it had to modify). 

Will creating a new `CALayerTree` work in this case? I tried calling it after I modified the colors, but it doesn't seem to make a difference. Thanks for helping me out!

**Comment by adamgit** [comment]
1. Parse the SVG (imageNamed)
2. Modify the SVGElements
3. call newCALayertree to force it to generate a new set of rendered output
4. add that to an SVGKImageView

If you want different views to display different images ... you will of
course need a separate SVGKImage object per imageview. Otherwise they'll be
sharing the same image, and display the same thing.

**Comment by Svantulden** [comment]
Unfortunately that was exactly what I was doing already, which did not work. I resorted back to the `[SVGKImage imageWithContentsOfFile:filePath]` function to workaround my problem. 

Amazing library by the way, it really fits my needs and it's easy to use!
