### ISSUE TITLE
iPhone 6/6 Plus support

### ISSUE THREAD

**Issue by genadyo** [SVGKit/SVGKit#215]
the devices are currently not support and the result is this assert:
NSAssert(FALSE, @"Not supported yet: you are using an iPhone that didn't exist when this code was written, we have no idea what the pixel count per inch is!");

**Comment by adamgit** [comment]
Fixed by #217 ?

**Comment by genadyo** [comment]
Thanks!!!

**Comment by JeanetteMueller** [comment]
Please bring up a new Release for use SVGKit with CocoaPods

**Comment by adamgit** [comment]
Last I heard, Cocoapods was blocking us from access, using a very badly 
designed new "authentication" system.

Cocoapods are definitely NOT supported at the moment.

There are a couple of people trying to get CP under control, but its a 
never ending task. Personally, I recommend avoiding CP until they learn to 
work with developers, instead of against us.

**Comment by JeanetteMueller** [comment]
oh shit :( pity to read. hope it gets better
