### ISSUE TITLE
Embedded image problem if CR

### ISSUE THREAD

**Issue by igorvlassov** [SVGKit/SVGKit#223]
Hello,
I tried to render SVG imported from SweetHome3D. It divided embedded base64 coded images on strings for better readability. In that case SVGKit fires abort signal. Could you process such images correctly please.

Thanks,
Igor

**Comment by adamgit** [comment]
We need an example test case, that is public domain (or you license for us
to include in the project samples), we need a specific description of what
went wrong, including line numbers and error messages, etc.

**Comment by adamgit** [comment]
That is illegal, according to the SVG Spec - base64 cannot contain newlines. Indeed, it is specifically advised that you use it only for short/small SVG docs because of line-length limits.

I recommend you contact SweetHome3D and inform them of their bug.

If you want to make it more robust, and share the actual error message etc, I'd add a specific error along the lines:

"You supplied an illegal SVG document. Please fix your SVG document, or use a standards-compliant SVG editor, and try again"

**Comment by igorvlassov** [comment]
Hello Adam,

thanks a lot for the clarification.

Regards,
Igor

14.11.2014, 14:45, "adamgit" notifications@github.com:

> That is illegal, according to the SVG Spec - base64 cannot contain newlines. Indeed, it is specifically advised that you use it only for short/small SVG docs because of line-length limits.
> 
> I recommend you contact SweetHome3D and inform them of their bug.
> 
> If you want to make it more robust, and share the actual error message etc, I'd add a specific error along the lines:
> 
> "You supplied an illegal SVG document. Please fix your SVG document, or use a standards-compliant SVG editor, and try again"
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Regards,
Igor
igorvlassov@narod.ru
