### ISSUE TITLE
Ability to handle SVG links; some kind of target-action hook?

### ISSUE THREAD

**Issue by idStar** [SVGKit/SVGKit#25]
I'm looking for the ability to define target-action links from SVG elements inside an SVG document. Does this framework support that? I'm guessing no, since I didn't see a class for the link element,  as there are for circles and other shapes/markup.

I'm new to SVG and SVGKit, although familiar with iOS Development.

If anyone has an example of doing this with SVGKit, or a fork they can point me to, that would be much appreciated.

**Comment by adamgit** [comment]
I _believe_ there's no support right now.

It should be easy to add.

I'd recommend trying my current branch: https://github.com/adamgit/SVGKit/tree/transforms -- because:
1. I've improved + simplified a lot of the XML / SVG Parser stuff, it's easier to extend now (and has better error reporting)
2. This branch sits on top of DOM - which _I suspect_ will make it easier to do some of the implementation of links. There are useful DOM methods for finding stuf in the SVG / XML tree.

NB: a lot of the DOM methods -- anything non-critical -- will error with "not implemented yet", and a copy/paste from the Spec of what they're supposed to do. If you encounter those, should be easy to implement them, most are VERY simple, and can be implemented using other methods that HAVE been implemented.

(I haven't imolemented them yet purely because there's so many to do!)

**Comment by adamgit** [comment]
PS: this will all get merged back into the main SVGKit soon.

**Comment by idStar** [comment]
Thanks for the info. I've been scouting capabilities here, as I may need to have SVG link capability for an upcoming project. I'll be back here to give your suggestions a try if that materializes.

**Comment by adamgit** [comment]
My fork now has some basic "link" support - I'm trying to get the complicated "svg:use" feature working.

Right now, it's not quite working :( - but the basic implementation is there, it probably just needs a small amount of tweaking.

**Comment by adamgit** [comment]
This basic support is now in the 2013base branch - but I haven't done any further work on it, so it's still not working.

**Comment by adamgit** [comment]
UPDATE: My USE / LINK code is merged into master now, but ... I couldn't fix the bugs. So it doesn't work - although a lot of the code is there, so it is probably quite easy to debug it and get it workign.

**Comment by adamgit** [comment]
It turned out my code had a typo - "x" instead of "y" - that was breaking it (someone else noticed and fixed it). This issue needs re-opening with the new code (if it's still a problem) - Closing for now, needs re-testing, many changes since this was opened.
