### ISSUE TITLE
Zooming in demo project.

### ISSUE THREAD

**Issue by lastMove** [SVGKit/SVGKit#255]
Hi, 
I am actually using your amazing frameworks.
I have just a little problem.
I know that it's probably because of apple Broken's api...
I am trying to use "pinch-to-zoom" with LayeredImageView. So I try it and retry, and finally I just changer SVGKLayeredImageView to fastImageView and it works like a charm.
But i need SVGKLateredImageView :) (I am making animations on the rendereds CAShapeLayers).

So. I try in the demo project.
The test case is pretty simple.
I just change this line:
`self.scrollViewForSVG.maximumZoomScale = MAX( 1, screenToDocumentSizeRatio );`
to
`self.scrollViewForSVG.maximumZoomScale =  4;`

And it the same problem. On Svgs using SVGKLayeredImageView (e.g the Monkey) it doesn't zoom. It's just bouncing.

I think that in fact, the SVGKLayeredImageView frame is normally zoomed. But the layers are maintained to their size

Do you have an idea to why it makes that?
Or just a suggestion that i can investigate?
Thanks for any helps.

**Comment by nimitz871016** [comment]
Hey, I have the same problem. You can try SVGKLayerdImageView.UIIMage. But it may cause new problem. An UIImageView will zoom when its bounds changed.

**Comment by lastMove** [comment]
I'am on the good way too find a workarround.
I don't think that user uiimage will work, since I am animating SGKLayeredImageView layers.
if you are using just SVGKLayeredImageView you can  delete the code in the "scrollview:didEndZooming" (from the demo project).
And then it will works pretty good for SVGKlayerdImage.
But the hit test will fail...
So if you need it:

``` ObjectiveC
    CGPoint p = [recognizer locationInView:self.contentView];

    CGPoint convertedPoint = [self.contentView convertPoint:p toView:self.scrollViewForSVG];

    CALayer *hitLayer = [self.contentView.layer hitTest:convertedPoint];
```

(in the handleTapGesture).
And then it should be OK.

**Comment by nimitz871016** [comment]
I'm trying to include both zooming and hittest in my project. So I used SVGKLayeredImageView. But since the hittest is ok, the zooming failed because when I changed the bounds the SVGKLayerdImageView didn't zoom. 
So I got a solution which is not perfom 100%.
I replace the SVGKLayerdImageVIew of its UIIMage in the scrollView when it begin to zoom. And recover it on the end. I keep the size of UIImage and set to a new SVGKLayerdImageView.
But hittest will faied and crash the app .I don't know why. I just set a simple subView in the SVGKLayerdImageView that cause this result. If I remove the subView, everything seems to be ok.

Sorry for my poor English.

**Comment by nimitz871016** [comment]
I have solved the problem.

 tempImage.size = CGSizeMake(tempView.bounds.size.width, tempView.bounds.size.height);
 ((SVGKLayer *)_mapView.layer).SVGImage = tempImage;

I make the SVGKLayerdImageView reload by setting a new SVGImage. And the subviews of the LayerdImageView deallocated in this process.
