### ISSUE TITLE
Indentation: tabs or spaces?

### ISSUE THREAD

**Issue by MaddTheSane** [SVGKit/SVGKit#257]
In an effort to cut down on white space noise, a few things would be convenient, like code formatting rules. The biggest one is the decision to use tabs or spaces for indentation. As it is,the code is a hodgepodge of these styles: I'd like to know which one is official.

The other formatting style choices aren't that much of an issue for me right now.

**Comment by adamgit** [comment]
Use tabs.

Github and git don't allow maintainers to tweak formatting on pull 
requests, so I'm not going to push people on this.

(Although ... Anyone who does a commit with lots of formatting changes, or 
particularly bad formatting ... will find it takes a LOT longer to get the 
pull request accepted, simply because its so hard to read)
