### ISSUE TITLE
How to resize rendered SVG UIView?

### ISSUE THREAD

**Issue by rmasfer** [SVGKit/SVGKit#27]
I could render the SVG image but i can not resize it to Screen size ? How to resize SVGDocumentView (UIView) ? 

Have anyone tried this before? Do you have any solution for this problem?

I'm so fed up now.. Please help me if you can.

Thank you..

**Comment by adamgit** [comment]
Please use my fork instead (has 100's of improvements - we will merge with main SVGKit very soon, but there's a lot of testing to do):

https://github.com/adamgit/SVGKit/

Instead of SVGDocumentView, use SVGKImageView - it behaves exactly like UIImageView, and resizing is simple: just set the "frame" property

**Comment by adamgit** [comment]
In the 2013base branch, you have two options:
1. Change the value of the "size" property on SVGKImage
2. Place an image into an SVGKImageView, and resize the frame/bounds of the image view
