### ISSUE TITLE
assertion when using animation uses defs.symbol

### ISSUE THREAD

**Issue by mr-fixit** [SVGKit/SVGKit#276]
My designer converted a Flash animation to SVG using https://github.com/TomByrne/Flash2Svg.

The SVG uses a 'defs' element that has a single 'symbol' element.   SVGKit throws an exception from SVGHelperUtilities.m:247 ("SVGSVGElement.parentNode == nil || [transformableOrSVGSVGElement.parentNode isKindOfClass:[SVGElement class]], @"I don't know what to do when parent node is NOT an SVG element of some kind; presumably, this is when SVG root node gets embedded inside something else?") because the parentNode is of class 'Element'.

The SVG _does_ render inside of Safari / WebKit, so I'm hoping I can get it to render via SVGKit.

A simplified version of the SVG can be found here: https://gist.github.com/mr-fixit/935b21c0f819867eb869.

**Comment by adamgit** [comment]
You need to tell us what caused the exception. Look in your debugger.

My guess is that animateTransform crashes it, since no-one has added any
animation support to SVGKit. It is extremely rare to find an animated SVG,
and most tools don't support it (e.g. the main reference editor (Inkscape)
didn't, last time I checked).

**Comment by adamgit** [comment]
If my guess is correct, you'd merely need to write
SVGAnimateTransformElement as per the spec, and it would prevent that
crash. Although it wouldn't animate, of course, unless you also write the
entire animation system for SVG.

**Comment by mr-fixit** [comment]
Hi Adam, thanks for the quick reply.

You said "you need to tell us what caused the exception".   I think I did that, both by saying "because the parentNode is of class 'Element', and by uploading a sample file that would allow anyone to see the exception in glorious detail.

I didn't realize SVGKit didn't do animation, thanks for that info.  I saw the "animate" button in the iOS demo project and assumed it did.  Looking closer, I see I was wrong.

**Comment by adamgit** [comment]
The exception is generic; you need to look at the SPECIFIC nodes that
triggered it (it could be any set of nodes in your file).

At the moment, lots of people are doing animation of SVG's - but they're
using Apple's CoreAnimation / Quartz library, that is a much more powerful
(and much more optimized) animation system than the ones built-in to SVG.

Partly this is because CA is also built-in to the whole of iOS, so ...
you're using it anyway, whether you want to or not :). You might as well
take advantage of it!
