### ISSUE TITLE
NSData support

### ISSUE THREAD

**Issue by EricShapiro** [SVGKit/SVGKit#28]
It would be nice if we could initialize an SVGDocument from an NSData rather than requiring a file path or url. We do our own downloading on specific queued threads and don't want SVGKit to download for us. (It's a minor issue, easily worked around)

**Comment by adamgit** [comment]
In my fork (will be merged with this soon), you can add a custom "source" by implementing "SVGKSource" - could you try this, and see if it works for you?

https://github.com/adamgit/SVGKit/

NB: asking because: we don't have any examples of NSData sources, so its hard to make an implementation that works as you expect (since I don't have a good use case)

**Comment by adamgit** [comment]
That fork is now merged as the branch "2013base" please try there.
