### ISSUE TITLE
Draw a pin in the map

### ISSUE THREAD

**Issue by alexliubj** [SVGKit/SVGKit#282]
Hi ,

I have a svg file which is a map.
I am wondering how can I draw a pin on the map when I tap it.
The pin is a png file.

Thanks,

**Comment by BrandonZacharie** [comment]
That is a general iOS programming question that is more appropriate for [StackOverflow](http://stackoverflow.com). Forgive me, I don't mean to be rude, but I ask that you close this issue and take it there because [there are 3 pages of open issues](https://github.com/SVGKit/SVGKit/issues) that are actually relevant and just [a handful of active contributors](https://github.com/SVGKit/SVGKit/graphs/contributors) addressing them. With that said, if you repost your question in detail on StackOverflow, I'd be happy to help.

**Comment by alexliubj** [comment]
Thanks,
