### ISSUE TITLE
Why does [SVGKImage imageNamed:@"dummy.svg"] need to assert agains nil and crash the app?

### ISSUE THREAD

**Issue by lukaszmargielewski** [SVGKit/SVGKit#287]
Can't it just return nil?

**Comment by adamgit** [comment]
I have no idea what you mean, sorry. Please read the notes at the top of
the page when submitting issues.

**Comment by kyrillc** [comment]
If we pass the name of a file that doesn't exist to [SVGKImage imageNamed:], then the assertion in [SVGKImage imageWithSource:] will make the app crash.
Could [SVGKImage imageNamed:] return nil when the file is not found, instead of making the app crash?
Or is it recommended to always check for the existence of the source file before creating a SVGKImage?

**Comment by adamgit** [comment]
Assertions will ONLY fire in your debug builds, so this has no impact on
live/production apps.

If I remember correctly: We had recurring bug reports of "library doesn't
work" because people provided nil params to the lower level method, often
because they passed in a non-nil value to a higher level method (e.g.
imageNamed: "some typo here.sGv") and then lost time chasing down the wrong
problem.

This gets especially tricky when loading SVGs over the network.

The assertion seemed a neat way of making it very easy to debug in
development (you should never be trying to load a  non-existent SVG!) while
seamlessly providing a clean safe implementation in production (nothing
goes wrong, you just get a blank image).
