### ISSUE TITLE
Drawing directly to a CGContext without using UIView or CALayer

### ISSUE THREAD

**Issue by cezarsignori** [SVGKit/SVGKit#31]
I am working on an app that renders shapes, lines, custom drawings into a single view (pretty much like a canvas). I am looking for a library to help me out with rendering SVGs on that same single view.

SVGKit enables me to do that by instantiating a view, so I can render that view's layer to an image or directly to my canvas. But I want to avoid having more than one view in my entire project, so I can use less memory space (I was having trouble on iPad retina having a view for each object on my canvas).

How can I use only the drawing logic of SCGKit without allocating a view or calayer for every SVG I want to render?

**Comment by adamgit** [comment]
I suggest using my fork:

   https://github.com/adamgit/SVGKit/

...where you can access the CALayers directly, without creating any uiviews, by calling:

   [SVGKImage newCALayerTree] // generates a set of calayers that you can safely "release" when you're finished

Alternatively, you could use:

   SVGKImage.DOMTree

...and re-write the entirety of Apple's render code so that you never need to use a CALayer. But that would be extremely difficult.

In the long run, it is almost impossible to render without allocating calayer's. But ... calayers (without UIVIews) are usually very very small amount of memory (and on retina: most SVG layers take no "extra" memory, since they are stored in vector co-ords, that don't change with the size of the image).
