### ISSUE TITLE
Refactoring PRs?

### ISSUE THREAD

**Issue by greghe** [SVGKit/SVGKit#315]
After working with this project, I've come to think that a few methods are overly-long and could benefit from being broken into several, more targeted routines. To be clear, I'm not proposing a wholesale rewrite, just some modest refactoring that would be careful not to break anything, and hopefully make the code easier to understand and maintain going forward.

I noticed that the `CONTRIBUTING.md` file refers to PRs that fix bugs or add features, but it doesn't seem to mention a PR that only improves the structure, organization and maintainability of existing source code. So, I'm wondering if this is the kind of PR that could meet this repo's acceptance criteria.  Thanks!

**Comment by adamgit** [comment]
For that, you'll need to email / IM us and talk it through first. I'm on adam.m.s.martin at gmail, and can CC others as needed.

There are plenty of areas that are unwieldy. Some of those can be replaced entirely (e.g. the XML parser is buggy; although by this point we have so many patches applied around it that it would be difficult to replace). Others are deliberately as-designed and should not be changed (e.g. SVGKImage, which has all the methods of UIImage: we don't want to change that, we just want to make the method implementations cleaner, and move other code to other classes).

So it's nuanced.

Also ... Some people don't realise that class names, method names, and class structure are fixed by the SVG standard. Refactoring them is not an option.

**Comment by greghe** [comment]
Thanks, that sounds reasonable. Closing.
