### ISSUE TITLE
Is CocoaLumberjack 2.x required in the podspec?

### ISSUE THREAD

**Issue by chrisballinger** [SVGKit/SVGKit#324]
This conflicts with some other pods we are using. 

Mainly I need iPhone 6 support which appears to be in the 2.x branch, but depend on Pods that require CocoaLumberjack 1.9.

**Comment by seltzered** [comment]
Technically yes, CocoaLumberjack 2.x introduced some changes in the naming conventions for calls. 

As an initial thought, I'm guessing you have two options:
1 - See if the other pods you use have development branches that have migrated to lumberjack 2.x and/or migrate them to it - IIRC, the changes I did for the SVGKit migration were essentially the following:
- DDLog.h is now `#import <CocoaLumberjack/CocoaLumberjack.h>`
-  Replace DDLogC\* stuff with just DDLog\* 
-  DDLogLevelWarn is now DDLogLevelWarning 

The full migration guide's in the CL readme ( https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/README.md ) 

2 - Since the changes are relatively recent, you _could_  temporarily pin yourself on commit https://github.com/SVGKit/SVGKit/commit/475ef2b7d2a3622f7e6065dbb3a72a6f9f8e16cf of the SVGKit 2.x branch.

**Comment by chrisballinger** [comment]
Yeah for now I've pinned to that commit. Such a painful transition because so many Pods are on 1.9 and there isn't really a compelling reason for authors to upgrade. It would have been cleaner if it was a hard fork...

Better would be a way for authors to support both versions to ease the transition.

**Comment by p2** [comment]
I'm not sure why, but when only using `pod "SVGKit"` my build fails, complaining about `DDLogCWarn` (implicit definition). With the following Podfile I can successfully compile.

```
pod 'CocoaLumberjack', '1.9'
pod 'SVGKit'
```

**Comment by adamgit** [comment]
We're now using Lumberjack 2.1.0 as a linked-framework. I'm guessing most libs are upgrading if not already (if they don't, you don't get tvOS compatibility from Lumberjack).

Re-open this if it's a problem, but I'm hoping you've managed to transition all your 1.x dependencies by now
