### ISSUE TITLE
does SVGKit support <symbol> tag now?

### ISSUE THREAD

**Issue by ChenWuLin** [SVGKit/SVGKit#334]

**Comment by ChenWuLin** [comment]
my svg file with <symbol> tag always crash when loading to app. does SVGKit not support <symbol> tag?

**Comment by mmmeff** [comment]
:+1:

**Comment by adamgit** [comment]
I don't remember anyone committing code for this, so probably: no.

If it crashes, there absolutely should be a clear message explaining why - have you looked at what happens? Have you read the instrutions shown when you filed this issue (they were at the top of the page).

If it crashes with no message, I suspect you've found a problem in the 3rd party XML parser or the way we're using it - IIRC "symbol" can trigger some weird XML semantics internally.

But I have no idea, since you've given zero information.

**Comment by mmmeff** [comment]
![selfie-0](http://i.imgur.com/dUCVhlF.gif)
