### ISSUE TITLE
Load an SVGKImage with width and height Autolayout constraints fails.

### ISSUE THREAD

**Issue by dani-mp** [SVGKit/SVGKit#340]
Hello.

In a Mac OS X app (10.10 and higher), I'm trying to load an SVGKImage in a SVGKLayeredImageView set in Storyboard using Autolayout.

If I set the layout constraints of the layered image view relative to its superview, this is, just margins, the image gets loaded properly, but resizing the superview.

If I set the layout constraints of the layered image view with a concrete height and width, and then center it on its superview, the image is not shown.

Is this a bug or am I doing anything wrong?

Thanks for the work done here. It's huge and awesome.

**Comment by adamgit** [comment]
Autolayout was severely buggy throughout iOS 8, and hard to use as soon as
you have complex apps - all the commercial projects I worked on dumped it.

This seems common. I think very few people are using SVGKit with Autolayout.

Also, with latest Xcode, Apple changed how Interface Builder interacts with
user-written classes.

So ... I suspect: this may have been correct originally, but is now
(accidentally!) doing something that breaks Autolayout. Fixes could be:
1. Possible, but unlikely: if it's a bug in Apple's code: Don't use
   Autolayout ;)
2. Debug how SVGKImageView classes interact with UIView. This CURRENTLY
   WORKS, but has never been tested with AutoLayout - it may need additional
   code to support AutoLayout
3. (PREFERRED / RECOMMENDED): Use the new features in Xcode that allow you
   to create an "SVGKLayeredImageView" template directly inside Interface
   Builder:

3.1. Change the demo project to use this.
3.2. Test it works.
3.3. If it works, try making a project with AutoLayout, and use the
newly-created Xcode item to add an SVGKLayeredImageView
3.4. Debug this.

I recommend option 3 because ... Apple often stops fixing bugs in their
code if there's a "preferred, newer" way of achieving the same thing. We're
NOT YET using the new Xcode GUI features; if you upgrade to those, your bug
might vanish!

(or ... the bug in our code that is breaking Autolayout might vanish
because it won't be running any more?)

**Comment by adamgit** [comment]
To be clear: with iOS 9, I suspect/hope that Autolayout has been fixed by
Apple and now works perfectly.

I would LIKE to move SVGKit to Autolayout; if Autolayout is now
production-ready, we should do that.

But AL has historically been broken and crappy; if it's still broken and
crappy, we won't use it.

**Comment by dani-mp** [comment]
In the point 3, what are the new Xcode features you're referring? I'm a bit lost. I can take a look at those and try it again, but I don't know what do you mean.

**Comment by adamgit** [comment]
I haven't had time to try them myself! But I believe you can now make
custom components in InterfaceBuilder, and provide your own render code to
make them be rendered (and editable!) directly in IB.

Previously, user-created classes were uneditable blobs. You had to create a
fake UIView in IB that you positioned, then at runtime in code delete it
and replace with your custom class.

We do something similar right now with the demo project - we can't
initialize an SVGKLayeredImageView directly in IB, we have to do the init
half in source code, which sucks. (because it's easy to forget). So we have
an automatic error / assertion that goes "wait - you can't use this in IB
unless you ALSO write some source code. Sorry!" or something like that.

**Comment by adamgit** [comment]
Please re-open if autolayout is still broken in latest xcode/SDK (xcode 7 seems to have fixed it a bit)
