### ISSUE TITLE
Hit test Issue

### ISSUE THREAD

**Issue by wasimshigri** [SVGKit/SVGKit#365]
The SVG Imageview gives hitTest for "rect" and "path". But it does not give the hittest for the layer of shape "line" . When i hits on the area of the shape "line" it gives the backgorund layer instead of that "line lyer". I dont know whats the issue. I have to get the line layer when i hit on it.  Any advice that can be helpful for this isse??  Will be thankful to you :)

**Comment by adamgit** [comment]
Ah! The problem is, I think: Lines are infinitely thin. It is physically 
impossible for you to touch one :(.

You need to think about this and decide what you want to achieve instead. 
Usually people want to ask "is the hit within x pixels of a line?" but 
apple doesn't provide that feature.

There are ways you can add it by hand. eg easy one is you can increase the 
thickness of the line, convert it from a line to an outline of the thicker 
line (apple has an api call that does this for you), and ask apple if the 
point is inside the outline.

But whether that's enough depends greatly in what you're trying to do.

If you get something working, sounds like a good feature to add - do a pull 
request and I'll review it and give you feedback, or approve it.

**Comment by wasimshigri** [comment]
Thankx for the reply .
Unfortunately its not the thicknes problem. The thicnkness of the line is already 40 px. :) i also tried by increasing the thickness of the line but the issue still exists there. 

What i am trying to do?
I wanna draw a path and i dont want to cross a type of layer(line). so for each  point in the path i am doing  hittest and checking either the layer i am getting by hittest is a line or not. 

I have many lines in my image(may be above thousand). I have  to find if i have hit on  any one of the lines or not. The check will go on continously (per second), so i cant make a forLoop on all the layers to check the bounds. 
Hittest is the fastest way thats why i am using this.So is there any solution for my problem?
 Or is there any other way fast like hittest using SVGkit to get the layer at any point in the view?
Thankx

**Comment by adamgit** [comment]
The math code for checking intersections of line segments is very very fast 
- you could intersect billions of lines per second in real time.

So ... i would try:
1. store the start/end points for each segment; you can fetch these from 
   the svg by using the various methods we have for searching the DOM for 
   specific tags etc
2. do the collision testing in your own code: do a line from last-Ok 
   position to current position.
