### ISSUE TITLE
Add tvOS Cocoapods support

### ISSUE THREAD

**Issue by Jeehut** [SVGKit/SVGKit#369]
I'd like to use this framework in a tvOS project using Cocoapods but in order to do this you need to explicitly state this project is made for tvOS, too.

For further details see [this blog post](http://blog.cocoapods.org/CocoaPods-0.39/).

**Comment by adamgit** [comment]
If they're saying library authors "must" change their source to fit the needs of an external system, that's absurd. If you need to do this, can't you just edit your
CP file?

If not, it sounds to me like a good reason not to support CP.

**Comment by seltzered** [comment]
I believe all that's needed is a change to the podspec file - @Dschee could you try adding in the modifications to the podfile and test it on tvOS? I recommend first creating your own fork, then in your podfile list reference svgkit to the local folder path. For example, I use svgkit (for an OSX app) via cocoapods, but the line in my podfile looks like this: 

```
pod 'SVGKit', :path => '../SVGKitMTSFork/'
```

As a reference to help in editing the file, check out the podspec on maddthesane's fork (see https://github.com/MaddTheSane/SVGKit/blob/master/SVGKit.podspec ) - there we do something similar in order to support OSX, and the podspec has helped in filtering out sources that are osx vs. ios specific. I'm expecting since tvOS / iOS are so similar, all you'll really need is the single deployment_target line. If all works definately send a pull req!

**Comment by Jeehut** [comment]
@seltzered Thanks for the help, I'll give it a try and report the results.

**Comment by Jeehut** [comment]
I tried and it didn't work in my case. So I'm opting for a manual integration via git submodules now. If anybody wants to try on their own project, here's how to add my fork:

– make sure you have the latest version of cocoapods installed (`gem install cocoapods`)
– simply add this to your Podfile: `pod 'SVGKit', git: 'https://github.com/Dschee/SVGKit'`

If it turns out other people seem to have no problem with it I'll be happy to send a pull request.

**Comment by dreampiggy** [comment]
Fix now. You can try using the CocoaPods version 2.1.0 via https://cocoapods.org/pods/SVGKit
