### ISSUE TITLE
SVGGElement CGRect

### ISSUE THREAD

**Issue by popwarfour** [SVGKit/SVGKit#379]
I'm running 1.2.0 from Cocopods master repo.

Getting the following exception thrown

```
sublayer with non-finite position [inf inf]
```

Looks like changing this line in SVGGElement.m (line 24) did the trick,

```
CGRect mainRect = CGRectNull;
```

to,

```
CGRect mainRect = CGRectZero
```

fixes the issue. Didn't look into it very deeply but I thought I'd bring it up. Thanks for the library!

**Comment by adamgit** [comment]
IIRC there's a difference. You can have a 0 0 rect specified, but RectNull
means never specified.

**Comment by popwarfour** [comment]
I think you are correct. CGRectZero is the same as (0,0,0,0) rect. The exception is shown here in SVGKImage+CGContext.m when I try and create UIImage,

```
- (void)renderInContext:(CGContextRef)ctx
{
    [self.CALayerTree renderInContext:ctx]; // exception thrown
}
```

This is the SVG that it doesn't like for some odd reason but my others seem to work just fine. So I'm not sure if that is what is actually causing the issue.
https://drive.google.com/file/d/0B8Q2EtU9zgjCQl84dE1HT1JRLW8/view?usp=sharing

Possibly a check for CGRectIsInfinite is needed in SVGGElement.m where you have the todo for isNull?

**Comment by adamgit** [comment]
I've looked at this now. CGRectZero is _definitely_ wrong and would break many SVG's. That would be stating that every single SVG includes the point (0,0) - which isn't true.

**Comment by PacificCoaster** [comment]
Usually, setting a rect to CGRectZero is a means to initialise the rect to a known state.
What you do after that is up to the logic of the your code.

```
Best Wishes,
    . . . . . . . .    Henry
```

**Comment by adamgit** [comment]
No, it is not. CGRectZero, in Apple's specific definition, means a rect
with a top-left corner at 0,0.

This has the effect that in Apple's library, if you union it with a rect at
100,100 of size 1, you get a rect of size 101,101 located at 0,0.

Maybe Apple staff didn't intend to define it that way - they were just
careless, and lazy about their testing (certainly, CoreAnimation has many
bugs in it), but ... that's why we had to use CGRectNull.
