### ISSUE TITLE
Missing header files in latest build

### ISSUE THREAD

**Issue by jtmilne** [SVGKit/SVGKit#383]
The following headers are missing from the Headers Build Phase:

SVGSwitchElement.h
CSSPrimitiveValue_ConfigurablePixelsPerInch.h
StyleSheetList+Mutable.h

**Comment by adamgit** [comment]
This used to happen a lot because of bugs in Xcode where it would silently
remove them when you added new files.

I haven't seen that bug in more than 2 years, I hoped Apple had fixed it
forever.

Can you see whose Commit removed them? e.g. using git Blame, or the History
/Blame features in Github? It might be that person is running a version fo
Xcode we need to watch out for!

**Comment by adamgit** [comment]
(I'm assuming those files are still in the project - I'm sure we'd have
noticed if someone had deleted them. i.e. you only need to drag/drop them
back into the Public phase)
