### ISSUE TITLE
Image caching option

### ISSUE THREAD

**Issue by LeonidKokhnovich** [SVGKit/SVGKit#399]
No ability to turn off global caching without modifying the library source code. I don't want to update it because the source code is included in my project as a submodule. I suggest allowing users to turn it on/off in run-time. We can still have ENABLE_GLOBAL_IMAGE_CACHE_FOR_SVGKIMAGE_IMAGE_NAMED and in the case when it is equal to 1 - we can add an additional run-time attribute.

**Comment by adamgit** [comment]
Current implementation should follow Apple's own library - imageNamed is cached (no choice), but if you manually specify an image source, it isn't.

Why do you want to turn it off?

NB: I added the compiler-switch ONLY because I thought Apple's implementation was a bit weird, and I felt some people (like me!) might not like it. In practice, I've found I leave it on all the time.

There is a small change I'd like to make in how it works, but everyone else seems happy with the current impl.

**Comment by adamgit** [comment]
NB: if we look at good caching, there are many, MANY, options to consider. Too many to add! Unless someone has a specific need for them.

**Comment by LeonidKokhnovich** [comment]
I asked that because in my app I generate a set of images dynamically using a template. The issue is that when I try to get a new template instance for further customization, it returns the instance of the previously modified image and since the application can still use that one, I would modify it across the application. Now I can't use "imageNamed" method and have to create a SVGKSource and then create a new SVGKImage from the new source. I believe the original UIImage implementation doesn't cache images across the app by default. But if you think that's not a big deal for most users - no problem, we can close the issue.

**Comment by adamgit** [comment]
UIImage _does_ cache images across the app by default. This confuses a lot
of people - it's very confusing when trying to trace certain bugs! - but we
_do not_ check if the file has been modified on disk since you last loaded
it (which I believe Apple does), so our caching is not as accurate as
Apple's :(.
