### ISSUE TITLE
Release 2.0.0 at Cocoapods/Specs repo

### ISSUE THREAD

**Issue by yzlai** [SVGKit/SVGKit#412]
There're only 0.0.1, 1.0, 1.2.0 releases in https://github.com/CocoaPods/Specs/tree/master/Specs/SVGKit/

**Comment by adamgit** [comment]
The CocoaPods team literally won't allow us to edit that.

I hate it; they grabbed our project, pretended their clone was "official",
then knowingly published incorrect, broken, links to it. I say "knowingly"
because we repeatedly told them so!

I have given up trying to get them to take it down. Please complain to them
directly.

If you get any response from them, please ask them to delete ALL of those -
none of them should be there, we want them all taken down. But at the
moment it seems we'd need to pay a lawyer and take legal action to get it
removed, since they've refused our (repeated) requests spanning several
years.

If they remove ALL of them, people will at least come to the main webpage
and get accurate, up-to-date files. Instead of being deceived by the CP
people.

**Comment by adamgit** [comment]
NB: to be clear - they previously maintained this data in their own private
DB. It may be they now use github as their master DB (?) and accept PR's
from anyone, in which case I'll happily PR a "delete all".
