### ISSUE TITLE
CocoaLumberjack optional

### ISSUE THREAD

**Issue by heyigor** [SVGKit/SVGKit#437]
CocoaLumberjack is too heavy to use. Please have it NOT be a dependency for this library.

**Comment by adamgit** [comment]
What do you mean "heavy"?

Off the top of my head, we're using these features:
- high performance logging (much, much faster than Apple's ASL defaults)
- user-configurable
- developer-configurable
- library vs app separately streamed and configurable + on/off
- re-routable to different output locations

If you want to write a replacement that does all those things, I guess you
could do so? I know ASL is richer than it used to be (I've used it on a few
projects instead of Lumberjack), but it still requires quite a bit of work
to make it do all this, last tim I used it?

**Comment by heyigor** [comment]
I'm using an alternate logging system, and including CocoaLumberjack ends up adding code to my project that will not be used. Unnecessary code, and added complexity for no benefit. I've modified other projects, by just overriding the CocoaLumberjack logging macros, but I'd rather not have to fork, etc.

**Comment by adamgit** [comment]
We cannot remove logging - that would destroy the project for most people,
and make support a nightmare.

Sounds like what you need is a meta-framework for logging that abstracts
logging but doesn't implement it. For most of us, Lumberjack provides this
already: it's open source, and every element is easy to override/replace
with whatever custom features/logging/etc you want.

It's not even strongly linked. We're using it as a framework, so can't you
write your own Framework that offers the same API calls and drop that in to
the project? It ought to work perfectly, and wouldn't use any Lumberjack
code, no?

**Comment by heyigor** [comment]
Completely understand, just wanted it a bit easier. I use a dependency manager, CocoaPods, and changing it support what I'd need means I'd have to fork. Which is fine.
