### ISSUE TITLE
Use of undeclared identifier LOG_LEVEL_DEF

### ISSUE THREAD

**Issue by beamercola** [SVGKit/SVGKit#481]
Using latest Xcode I'm getting this error.  Can bypass this if I `#define` them to `0`, but doesn't seem like a long term plan

**Comment by adamgit** [comment]
Is this in SVGkit or in Cocoa Lumberjack (the logging framework we use)?

**Comment by Nonouf** [comment]
This is due to CocoaLumberjack 2.4.0. 
I haven't dig more in the problem yet but a quick workaround is to use the version 2.3 of CocoaLumberjack, which you can specify yourself in your Podfile.

**Comment by adamgit** [comment]
So ... someone needs to upgrade Lumberjack version in SVGKit and issue a
pull request :) ?

On 30 September 2016 at 12:15, Arnaud Schildknecht <notifications@github.com

**Comment by delebedev** [comment]
@adamgit I have the same issue as described in initial post. Bad thing is that `CocoaLumberjack` now has 3 as major version.
1. Does SVGKit really need to depend on relatively "heavy" logging framework?
2. If yes, SVGKit has to be released with major version bump + updated `CocoaLumberjack`, am I getting it correctly?

**Comment by adamgit** [comment]
Updating the Lumberjack version is usually very quick and easy. Last time
it happened, I think we didn't even have to change any classes - just
overwrote the old version with the new one :)

**Comment by delebedev** [comment]
@adamgit I'm up for making a PR with updated CocoaLumberjack. However I have doubts regarding including prebuilt binaries in 3rd-party-frameworks folder. Which version of Xcode should I use? 8, 8.1, or 8.x when it comes out? CocoaLumberjack has a piece of swift in it and as we all know bundling prebuilt swift code is error prone.

**Comment by adamgit** [comment]
Ideally Xcode 7, since that's the current robust/mature version - although IIRC Apple's now made 8 compulsory for app-store already? (desperation, I guess - so many devs refusing to upgrade because xcode x.0 and x.1 releases always suck so bad? :))

If you're worried about difficulties here: ... Is there a better way to bundle CL going forwards?

Requirements:
1. If you download the SVGKit repository, you can build + run out of the box, no additional downloads needed --- this is critical! We had huge problems with people getting confused with missing 3rdpary bits, until we moved to this requirement.
2. IMHO: CL should be included in each SVGKit project as a .framework, so that users can easily replace/upgrade it by drag/drop.

We recently did a big refactor at my dayjob to get frameworks-in-frameworks working beautifully. Still multiple stupid bugs in Xcode we had to workaround :(, but I imagine we want something similar for CL.

(net effect: Library A is used (as a framework) by Library B, which ships as a second framework. ... then Application C has to embed both frameworks, making it very easy for Application C to change the version of Library A it's using, so long as that version is backwards compatible with the version it replaces)

...if this seems a better setup, I can help on setting that up, having just done it :)

**Comment by odrobnik** [comment]
What is the recommended workaround for using SVGKit via Cocoapods and getting this error?

**Comment by philipacrowe** [comment]
@odrobnik Has there been any update on this? I can't build one of our projects since upgrading to xcode 8, I'm getting:

Use of undeclared identifier 'LOG_LEVEL_VERBOSE'
in the SVGKit-prefix.pch

I've tried setting the pod to 2.3 but get the same error:
pod 'CocoaLumberjack', '~> 2.3'

**Comment by odrobnik** [comment]
@philipacrowe no update. I decided to not use this project and instead went with my own SVG parser and renderer which I wrote in Swift.

**Comment by dcflow** [comment]
@philipacrowe @odrobnik easy just use 
`pod 'SVGKit', :git => 'https://github.com/dcflow/SVGKit.git', :branch => '2.x'`

**Comment by cpboyd** [comment]
@philipacrowe That will still result in 2.4 being selected.  You probably meant `'~> 2.3.0'`  (Which is anything below 2.4)

@rygood I don't know if limiting to 2.3 is really a solution, as people may want to use a later version.

What you can simply do for 2.4 and later is make a change in SVGKit-prefix.h:
```
-    #import <CocoaLumberjack/CocoaLumberjack.h>
+    @import CocoaLumberjack;
```

This is described at https://github.com/CocoaLumberjack/CocoaLumberjack/issues/778

**Comment by polaris-dxz** [comment]
Use of undeclared identifier 'LOG_LEVEL_VERBOSE'问题

解决办法：https://my.oschina.net/ioslighter/blog/381201

懒得写英文了。。
