### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by jberkhei** [SVGKit/SVGKit#482]
Demo project doesn't seem to build

**Comment by adamgit** [comment]
Did you read the instructions at the top of the screen when you created 
this issue?

**Comment by jberkhei** [comment]
Yes, instructions state:
Open up "Demo-iOS.xcodeproj", and run it (on simulator or device).

**Comment by adamgit** [comment]
No, the instructions at the top of the page when you submit a new issue.

**Comment by jberkhei** [comment]
Far enough.  A short description of the issue:
I downloaded the project, simply tried to run the demo project and ran into the error above.  I tried the deleting the derived data directory as this seems to be an common xCode issue but it did not seem to help.  Do I need to build any of the libraries prior to running the demo project?  From the instructions it appeared that it would run out of the box.

**Comment by adamgit** [comment]
You're right it runs out of the box.

So presumably there is an issue with the specific version of xcode you're
running, or the target you're running on.

But you haven't given any info, so I can't comment on that - I can only
guess that it might be part of a problem.

**Comment by oiledCode** [comment]
I'm experiencing the same problem, trying to build the static library. The problem is related to the run script phase, in particular the incriminated line is :
`SDK_VERSION=$(echo ${SDK_NAME} | grep -o '\d\{1,2\}.\d\{2\}$')`
basically grep fails. I'm not an expert on grep so I did not find a fix yet.
My env is : Xcode 8 - sdk iphoneos10.0

**Comment by oiledCode** [comment]
Found a fix for the script, basically Ive replaced 
`SDK_VERSION=$(echo ${SDK_NAME} | grep -o '\d\{1,2\}.\d\{2\}$')`
with this 
`SDK_VERSION=$(echo ${SDK_NAME} | grep -o '[\\.0-9]\{3,4\}$')`

**Comment by adamgit** [comment]
Ah. Damn. Try this:

SDK_VERSION=$(echo ${SDK_NAME} | grep -o '\d{1,2}.\d{1,2}$')

The range based version is even more of a hack than the original :).

**Comment by jberkhei** [comment]
I'm running into this issue with xCode 7.3.1

**Comment by adamgit** [comment]
From what @oiledCode wrote, the demo project should still run fine with no problems - the error they've got is only triggered when you manually build the static library.

You need to click the error in your xcode and find out what it actually is, and where it is. The title of this issue is only a sumary, not the real error.

If it turns out to be the same problem as @oiledCode , you need to:
1. Go into build settings 
2. Find the tab with Build Phases
3. scroll down to the bottom, a "run script" phase
4. Edit the script, find the line that looks like the code we pasted above (it's near the start)
5. Replace it with the one I pasted above (which is only 1 letter different, but should fix that problem)

If it works - do a pull request and I'll merge your change! (I don't have access to a dev machine today, I can't run xcode right now - I'm on ipad + phone)

**Comment by jberkhei** [comment]
Thank you for hanging in there with me.  That resolved the issue.

**Comment by adamgit** [comment]
Can you commit the change and submit a pull request (one click on github.com
site) ? Then it'll be fixed fore veryone
