### ISSUE TITLE
loading svgs asynchronously

### ISSUE THREAD

**Issue by tsaizhenling** [SVGKit/SVGKit#54]
I'm having problems loading the svgs asynchronously. My guess is that SVGKit is not designed to parse multiple SVGs asynchronously to begin with.

I did a test on the demo project 
I added  to MasterViewController.m

```
- (UIImage*)imageFromView:(UIView *)view
{
    // Create a graphics context with the target size
   // On iOS 4 and later, use UIGraphicsBeginImageContextWithOptions to take the scale into consideration
   // On iOS prior to 4, fall back to use UIGraphicsBeginImageContext
@synchronized (self) {
    CGSize imageSize = [view bounds].size;
    if (NULL != UIGraphicsBeginImageContextWithOptions)
        UIGraphicsBeginImageContextWithOptions(imageSize, NO, 0);
    else
        UIGraphicsBeginImageContext(imageSize);

    CGContextRef context = UIGraphicsGetCurrentContext();

    // -renderInContext: renders in the coordinate space of the layer,
    // so we must first apply the layer's geometry to the graphics context
    CGContextSaveGState(context);
    // Center the context around the view's anchor point
    CGContextTranslateCTM(context, [view center].x, [view center].y);
    // Apply the view's transform about the anchor point
    CGContextConcatCTM(context, [view transform]);
    // Offset by the portion of the bounds left of and above the anchor point
    CGContextTranslateCTM(context,
                          -[view bounds].size.width * [[view layer] anchorPoint].x,
                          -[view bounds].size.height * [[view layer] anchorPoint].y);

    // Render the layer hierarchy to the current context
    [[view layer] renderInContext:context];

    // Restore the context
    CGContextRestoreGState(context);

    // Retrieve the screenshot image
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();

    UIGraphicsEndImageContext();

    return image;
}
}

- (void)renderAll {
dispatch_queue_t renderingQueue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);

for (NSString *name in _sampleNames) {
   // dispatch_async(renderingQueue, ^{ // uncomment this line to perform tasks asynchronously
        SVGKImage *document = [SVGKImage imageNamed:[name stringByAppendingPathExtension:@"svg"]];
        NSLog(@"document: %@",document);
        SVGKFastImageView *imgV = [[SVGKFastImageView alloc]initWithSVGKImage:document];
        UIImage *img = [self imageFromView:imgV]; // and do something else with it
        [imgV release];
  //  }); uncomment this line to perform tasks asynchronously
}
}
```

they initialise the vector and rasterises them. (removed @"Reinel_compass_rose" because it crashes) (also disabled global caching)

crashes only happen when the tasks are done asynchronously with various exceptions like
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString setString:]: Range or index out of bounds'. 
or
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This node has no valid SVG tags as ancestor, but it's not an <svg> tag, so this is an impossible SVG file'
or 
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM removeObjectAtIndex:]: index 2 beyond bounds [0 .. 1]'
and perhaps more i have yet to find

[SVGKImage imageNamed:[name stringByAppendingPathExtension:@"svg"]]; also returns null when performed asynchronously

**Comment by tsaizhenling** [comment]
I managed to avoid crashes by sychronizing in 

```
+ (SVGKImage*) imageWithSource:(SVGKSource *)newSource
+ (SVGKImage*) imageWithContentsOfFile:(NSString *)aPath
+ (SVGKImage*) imageWithContentsOfURL:(NSURL *)url
```

but am not sure if they are the best places to place semaphores, I may be synchronizing more parts of the code than neccessary

**Comment by adamgit** [comment]
1. no need to say it ends in .svg - that's done autoamtically
2. no need for custom image code - use SVGKIamge.UIImage
3. due to a MAJOR bug in the libxml parser (not fixed for many years) the SVGKParser.m class is not thread-safe. ---- this is what's causing your crash, I'm 100% sure

What to do about this?

PROBABLY: the best thign is to replace your 3 x synch's with 1x synch in the [SVGKParser parse] method.

It would be great if you could:
1. try that
2. issue a pull-request to master so we can merge this in if it works :)

**Comment by adamgit** [comment]
NB: long-term ... someone needs to delete libxml (!) and replace with a better XML parser (good luck finding one :( ) ... or come up with some "clever" convoluted workaround for the libxml bug.

FOR FUTURE READERS: the problem: "libxml corrupts mem internally if you provide it with a pointer to your "already parsed" data. Lots of XML parsing needs to look at the "data parsed so far" in order to decide what to do with the current node".

The solution: currently, we assign a CLASS variable "current parse data". This is why the parser is NOT thread-safe.

A thread safe solution: somehow fake a CLASS varible PER INSTANCE OF THE PARSER --- I _blieve_ this can be done using "Objective-C Associated Objects" -- google for more info

**Comment by adamgit** [comment]
This MIGHT now be fixed, with this patch: https://github.com/SVGKit/SVGKit/commit/1081a69c1aaa3f160a9d303d638fc953ac03f5f8

Please try it and see
