### ISSUE TITLE
Black icons

### ISSUE THREAD

**Issue by NuVeS** [SVGKit/SVGKit#548]
### New Issue Checklist

See black icons on using SVGKit. It parses, but i see black figure of my image without colors. What is wrong? 
let image = SVGKImage(dataAsynchronously: data.data, onCompletion: { (image, result) in })
let view = SVGKFastImageView(svgkImage: image)
view?.frame = (self?.logoImageView.bounds)!
self?.logoImageView.addSubview(view!)

**Comment by adamgit** [comment]
Console log?

**Comment by NuVeS** [comment]
No log information...

**Comment by ezisxl** [comment]
also have this if using from cocoapods. if downloading the sample then the tile loads ok :/
![simulator screen shot - iphone x - 2018-11-22 at 13 39 55](https://user-images.githubusercontent.com/4365368/48900838-2b8f1780-ee5c-11e8-96ed-fde0d2965922.png)

**Comment by adamgit** [comment]
Then there's something wrong with your cocoapods setup.

As per the front page of the project: due to too many problems with cocoapods (and the fact they have been telling people to download a dead, unsupported, version of this project for many years, despite being asked not to), we don't support cocoapods at the moment.

Dreampiggy is trying to get that all fixed at the moment - in theory, the 3.x branch has a cocoapods setup that works.

As per the frontpage: You should be using 3.x for everything unless you have a specific reason not to.

**Comment by ezisxl** [comment]
thx!
`pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'`
solves this!

**Comment by adamgit** [comment]
Ouch, sorry - none of us noticed the README still said 2.x. I'll fix that now. Thanks!

**Comment by Revanth-Kausikan** [comment]
Can someone point out the cause/fix for this?
