### ISSUE TITLE
App Crashing as *** Assertion failure in +[SVGKImage imageWithSource:]

### ISSUE THREAD

**Issue by VishnuV02** [SVGKit/SVGKit#561]
Hai,

* I am working with SVGKit in swift Project. I properly imported SVGKit Framework and 3rd party resources folder into my project by following (https://github.com/SVGKit/SVGKit).
* I created a folder with sets of .svg images inside the project and i am using the following code to load image into testIcon(ImageView).
   let lockImage: SVGKImage = SVGKImage(named: "LockIcon.svg")
   let lockImageLocal: UIImage = lockImage.uiImage
   testIcon.image = lockImageLocal
* But i am receiving the following error,
        ** Assertion failure in +[SVGKImage imageWithSource:], /Users/fss/Downloads/SVGKit-    
            2.x/Source/SVGKImage.m:229
       *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason:   
             'Invalid parameter not satisfying: newSource != nil'

Please let me know how to mention path of .svg image(which is inside my project) to SVGKImage image class or how to resolve this problem.

**Comment by adamgit** [comment]
Apple removes all paths when the app us built, so that shouldn't matter.

Look at the source for thr svgkimage method you're using - you'll see it is 
a few lines of code wrapper for using a more powerful init method that lets 
you provide an SVGKImageSource.

You can copy that and do the same yourself, allowig you to look at thr 
SVGKImageSource in debugger and see if its returning nil and why.

My guess: you arent including thr image in your project.

**Comment by kalidoss73** [comment]
am also facing this kind of error 

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: newSource != nil'
***`

**Comment by adamgit** [comment]
As per previous response: this exception usually means there is a bug in your code. You are providing an missing file / invalid path / missing resource / etc.

If you look at the xcode debugger, it should tell you what's going on, and you can figure out where your code is failing
