### ISSUE TITLE
Remove CocoaLumberjack

### ISSUE THREAD

**Issue by SilinVasya** [SVGKit/SVGKit#573]
Hi, guys.

My question is very simple:
Could you remove CocoaLumberjack from SVGKit dependencies, so no need to install additional pod to the project?

I don't think SVGKit requires CocoaLumberjack to work.

**Comment by adamgit** [comment]
Svgkit uses lumberjack for all logging.

**Comment by SilinVasya** [comment]
Yes, you are right.

But, my question still the same:

SVGKit doesn't need CocoaLumberjack for SVG processing, but only for logging.
It's additional project dependency. I don't think everyone use CocoaLumberjack for logging, so it isn't a good practice to keep additional dependency, just for logging.

I am using SwiftyBeaver, and it looks bad that project has two loggers.

Is it possible to remove CocoaLumberjack as project dependency?

**Comment by adamgit** [comment]
You cannot have good code without logging. Svgkit has to work not for one 
project, but many many projects. Logging is essential to preventing new 
bugs and finding old ones.

So, yes, it needs logging for processing. Many bugfixes and new  features 
only happened because of the logging. Many people who got stuck, had bugs 
in their own code (not bugs in svgkit! ) were able to find and fix their 
bugs thanks to the logging.

If you really want to downgrade it you can add a #define to enable/disable 
logginf globally,  and then #if every individual logging call (see how long 
this  takes - there's a lot of logging in the project), and then delete 
Lumberjack (and easily put it back when you need logging yourself). You get 
the best of both worlds that way, I think.

I have never seen a project "look bad" because it uses multiple logging 
libraries. Unless you're on a platform with a standard logging API (Apple 
almost provided this, but didn't want an open solution) that makes all the 
logging libraries compatible, then... it's inevitable that you'll have more 
than one.


I can't remember who chose Lumberjack, but at the time it was the most 
popular, fastest, logging library on iOS, so it was the one most people 
wanted to use.

**Comment by vitalii-tym** [comment]
Hey, @SilinVasya.
I had serious problems with CocoaLumberjack in my project some time ago, so I was forced to remove it. You can check my fork here: https://github.com/vitalii-tym/SVGKit/commits/without_CocoaLumberjack
But note that I had no time to test it after recent merge from upstream. Try yourself and drop a note if it still works or not.
Hope this helps.

**Comment by SilinVasya** [comment]
Hi, @vitalii-tym 

Sounds great.
I will try it.

Thank you.
