### ISSUE TITLE
SVG image rendering issue

### ISSUE THREAD

**Issue by kritikaperiwal12** [SVGKit/SVGKit#619]
I have a SVG image file and the task is to parse that image. I am able to show image by parsing different layers of image using Pocket SVG but vales of text tag is not showing. Main issue and the task of parse SVG that is pending is text not appearing on the SVG only.
I also try to use different framework i.e. SVGKit, Swift SVG. But in both these caes i am not able to parse the different layer of image. But using Pocket SVG i am able to parse the SVG. Issue is of text only.
 Can anyone help me.

Link of SVG image file:  https://drive.google.com/file/d/1kdoApJ606kCXd8tfYqWGjAqs_BTOhY94/view?usp=sharing

**Comment by adamgit** [comment]
As per the instructions when you created this issue, you need to do some work yourself. We cannot read your mind. You need to explain what is wrong, what you expected to see, and what you actually saw. You may need to use the debugger to figure out what the problem is (or what it probably is).

If you do that, other people can help. They may even be able to suggest fixes. If you do not do that, no-one is going to do it for you.

PS: Google Drive is a bad place to host images - Google blocks people from viewing SVGs. I can't see your SVG.

**Comment by kritikaperiwal12** [comment]
@adamgit 
I will take care of this thing in my future posts. Please don't close this post. It is urgent for me.

**Comment by adamgit** [comment]
If you add information about what is wrong, what isn't working, what you saw in debugger, where SVGKit is failing, etc ... I will re-open the issue.

But currently: this is not an issue. If you don't want to debug this yourself, I suggest you go to freelancer.com or similar and ask for help there.

**Comment by kritikaperiwal12** [comment]
@adamgit 
I edit my issue. What i exactly want and what i am getting.

**Comment by adamgit** [comment]
OK. It sounds like you are asking for help with Pocket SVG. That is a different project - you need to speak to the maintainers of PocketSVG for help.

**Comment by kritikaperiwal12** [comment]
@adamgit Ok. Thanks for the info and correcting me.
