### ISSUE TITLE
how to resize SVGKLayeredImageView

### ISSUE THREAD

**Issue by tsaizhenling** [SVGKit/SVGKit#63]
I was using SVGKFastImageView but am finding that I am unable to avoid gradients.

I used to set the frame of SVGKFastImageView and the content would resize as expected.

SVGKLayeredImageView unfortunately does not.

how should i be resizing the  content of SVGKLayeredImageView?

**Comment by adamgit** [comment]
We had to change resizing to workaround / fix some other issues.

(and the SVG spec says we were doing it wrong anyway :( )

What you should do now is set the .size property. This will CORRECTLY set the SVG size (according to spec) AND set the Apple size.

...or you can manually update the SVG Viewport (which is what the spec requires, and is what .size property is doing automatically for you)

**Comment by sarperdag** [comment]
Now that I'm using SVGLayerImageView, I'm having this problem too. And this time, I can't find any .size property under SVGKLayeredImageView...

What am I doing wrong?

**Comment by sarperdag** [comment]
oh there is one under SVGKImage, but changing it doesn't really affect anything?

**Comment by sarperdag** [comment]
Actually, [svgImage setSize:CGSizeMake(100, 100)]; works on its own but when the frame of SVGKLayeredImageView changes, if you update to a new size using [svgImage setSize], it doesn't affect the image...

**Comment by adamgit** [comment]
@sarperdag I'm sorry this isn't clearer, but ... as soon as you render an SVGimage, it becomes "disconnected" from the SVG in-memory.

You _cannot_ change the image / CALayers and expect the SVG to update.

This is because:
1. the model we're using is "one SVGKImage can generate multiple independent renders - you can make tweaks to the SVG-image, then regenerate new CALayers, and the old layers remain unaffected" 
2. it would be a lot of work / sourcecode to somehow "convert Apple CALayers and UIViews into valid SVG documents". That would be REQUIRED in order to make changes reflect backwards the way you describe. If someone wants to write an "Apple GUI -> SVG imagefile" converter, we could use that - but it's almost a whole project in its own right :)
