### ISSUE TITLE
SVGKLayeredImageView - problems with zoom

### ISSUE THREAD

**Issue by Lopdo** [SVGKit/SVGKit#65]
Hey, I am trying to show big svg file in my app. I am using SVGKLayeredImageView because I need to be able to select parts of that image. It doesn't fit on the screen so I had to put it in scrollView and enable zoom. However, when I zoom in or out the image gets moved and I can't see it anymore. It gets moved because of
     -(void)scrollViewDidEndZooming:(UIScrollView *)scrollView withView:(UIView *)view atScale:(float)finalScale

When I comment it out, it works fine.

Second issue I am having is that the touch position is not correctly calculated when I am zoomed out. It works properly only when image is displayed 1:1, any other zoom value produces wrong touch positions

**Comment by adamgit** [comment]
That method doesn't exist in the library, so I don't know what you're doing - perhaps you're using some of the demo code and adapting it?

Re: touch position - this should be working perfectly, I expect there is something wrong with your code for touches. Lots of people get this wrong because they misread Apple's docs (nothing to do with SVGKit). There was a recent commit from someone that _might_ have affected this - but I haven't seen any problems in my apps. If you can produce a simple test case and attach it we can re-open, otherwise I'm afraid you need to re-read Apple's docs.

**Comment by khawarshzd** [comment]
I am also facing both of these issues.
Fixed first one by commenting out the code, but still worrying about second issue of inaccurate touch positions when zoomed out.

**Comment by adamgit** [comment]
We need a test-case that demonstrates the problem, and is integrated into the "SVGKit-iOS Demo" project.

If this needs a particular combination of SVG file + UIScrollview + scroll settings ... you'll need to add them for _this_ case without changing all the existing ones. The current setup (a list of SVG files you can tap on) isn't a great UX, so feel free to convert it to a better system that makes it easy to do your new test.

Until then ... I'm afraid you're on your own. If we can't easily test it, no-one's going to try and fix it for you, sorry.

**Comment by objective-d** [comment]
This is a simple fix:

Because you are no longer using the code in scrollViewDidEndZooming:withView:atScale (which as you point out, doesn't work), you need to convert the coordinates of your SVGLayerImagedView into the same coordinates system as its parent (in this case, the scrollview).

To do this, use something like:
- (void)SVGViewWasTapped:(UITapGestureRecognizer *)recognizer
  {
  // coords of tap - this is in the SVGLayerImageView coordinates system
  CGPoint p = [recognizer locationInView:self.viewSVG];
  
  //convert to superview coordinates system
  CGPoint convertedPoint = [self.viewSVG convertPoint:p toView:self.scrollView];
  
  // do your hit test
  CALayer *hitLayer = [self.viewSVG.layer hitTest:convertedPoint];
  
  //indicate which layer was tapped
  if (hitLayer)
      hitLayer.backgroundColor = [UIColor redColor].CGColor;
  }
