### ISSUE TITLE
Stop whining

### ISSUE THREAD

**Issue by morgendagen** [SVGKit/SVGKit#71]
This is a rant, but looking at the comments in the SVGKit source code I expect the SVGKit-developers to be able to cope with that.

Searching for a way to render SVG files in an iPhone app, I stumbled upon SVGKit, which looks like the most mature implementation. Since we need better support for text in our app than SVGKit currently provides, I started looking in to enhancing SVGTextElement.

First thing I noticed when I started looking in to the source code was a huge number of comments about bugs in Apple's API's, stupid decisions made by the SVG team, and comments about bad code submitted by other developers. I must say I was quite surprised by the number of comments about bugs in Apple's APIs, since I have been doing quite a bit of Core Animation development without running in to major issues.

After spending two days figuring out how to interpret SVG, and looking at the SVGKit code to figure out the architecture, I managed to add basic support for tspan elements (x,y,dx,dy,fill,font-family,font-size,font-weight) while at the same time fixing the issue where SVGKit renders very blurry text when zooming. Without running in to any bugs in Core Animation :-) Hint: CATextLayer is not a good choice when implementing SVGTextElement.

If the attitude of the developers of SVGKit is to bitch about everybody else, I have no desire to help out on the project, but on the other hand I would really like a good SVG rendering engine for iOS...

For the time being I have forked SVGKit, and will continue my development on that fork - removing stupid comments on my way.

Best regards

Peder

**Comment by adamgit** [comment]
Github has a nice forking tool. If you look carefully, you can see the MANY times that people have accidentally submitted patches that they thought were fixing things - but which broke existing projects because they didn't realise the original code was a workaround for Apple's bugs.

Github has a nice issue tracker. It shows you how many times we get people logging "bugs" against things that are part of Apple's libraries, not part of SVGKit.

Github has some nice graphs. They show you the vast number of hours of work that have gone into SVGKit to get it to where it is.

What Github can't tell you is the vast number of hours wasted by contributors trying to implement code as per Apple's libraries only to find that the library docs are wrong.

**Comment by adamgit** [comment]
"CATextLayer is not a good choice when implementing SVGTextElement"

Yes. This project is implemented by volunteer contributors. They use whatever they can find that seems best at the time. We do code-reviews on every pull request - but if it's using libraries that no-one else has used much before, and it looks correct (and, most importantly: it works with all the test-cases), then we're going to OK it.

If you know an area well - e.g. custom Text-rendering - everyone would love you to do it better. Much of the code in SVGKit is stuff that none of us are proud of :) - but as a whole it works well enough for use in production apps, which we are proud of.
