### ISSUE TITLE
Speed up or mask render time for SVGs

### ISSUE THREAD

**Issue by againes** [SVGKit/SVGKit#72]
We are trying to figure out a way to speed up or mask the render time for larger SVG images. We are rendering them async with GCD now. We were curious if there is a way to serialize out the render data somehow and load it back in so that the app does not have to re-render the SVG files each run.

**Comment by adamgit** [comment]
SVGKImage has a property ".UIImage" that returns a raster based on the current data (including any scaling you've applied).

Or, if you want to go really fast, use [SVGKImage exportNSDataAntiAliased:curveFlatnessFactor:interpolationQuality:flipYaxis: ] -- that method doesn't even generate an image object, it just rasters direct to raw bytes, in RGBA, which you can e.g. feed directly to the GPU (with OpenGL ES) for very fast "load SVG -> render to texture -> draw on screen".

(I added this specifically so I could render SVG's as texture maps onto OpenGL 3D objects, and it works well.)

**Comment by adamgit** [comment]
More generally ... there are some performance bottlenecks in the low-level string-parsing of the XML files that store SVGs. Several contributors have reported big improvements on large files, but none were stable enough / finished enough to merge into master.

(from memory: if you Profile using the built-in tools with Xcode, you see lots of string reading / creation as a bottleneck. It's pretty easy to re-factor that code with faster string-parsing method calls, it's just boring and tedious to write!)

**Comment by adamgit** [comment]
Finally ... SVGKImage is designed so that it works in discrete stages:
1. Read data from web/disk/RAM
2. Parse the XML/SVG, converting to in-memory DOM / tree of SVG\* classes
3. Export the SVG classes to Apple CALayer render classes
   (4. Optional: further export the CALayer classes to a rasterized bitmap)

You can easily save the output of 2. above, and then reload it by overwriting the value of ".DOMDocument" and ".DOMTree" on SVGKImage (might require some care with importing the special header that makes those properties writeable).

But on large images, a LOT of the overhead is some surprisingly slow code inside Apple's CALayer APIs, where they seem to be doing stuff in software that should be in hardware. The ultra-hardcore approach would be to re-write some of the CALayer classes using your own custom OpenGL rendering code!
